---
version: '3'
services:

  fusiondirectory:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - SLAPD_PASSWORD=passldap
        - SLAPD_ORGANIZATION="Demo Fusion"
        - SLAPD_DOMAIN=demo.fusion
    network_mode: host
    volumes:
      - ldap-data-db:/var/lib/ldap
      - ldap-data-etc:/etc/ldap
      - fusion-data-share:/usr/local/share/fusiondirectory
      - fusion-data-etc:/etc/fusiondirectory

volumes:
  ldap-data-db:
  ldap-data-etc:
  fusion-data-share:
  fusion-data-etc:

networks:
  default:
